### ISSUE TITLE
Test descriptions

### ISSUE THREAD

**Issue by cjessett** [GonzaloGM/CodecademyTDDVidBits#3]
(Subtlety) It's not necessary to nest the HTTP verbs inside the endpoint description. Especially since you only have 1 verb per route. https://github.com/GonzaloGM/CodecademyTDDVidBits/blob/master/test/routes/videos-test.js#L9

Conventionally (for readability and clarity) we describe route tests like so:
```
describe('GET /videos', () => {
  it('does what we need it to do')
})

// in general
describe('<HTTP verb> <endpoint>', () => {
  <assertions>
})
```

**Comment by GonzaloGM** [comment]
@cjessett That makes so much sense, it was a little bit weird when I was nesting it like that. Thank you!
