### ISSUE TITLE
Test scenarios

### ISSUE THREAD

**Issue by cjessett** [GonzaloGM/CodecademyTDDVidBits#4]
(Important) https://github.com/GonzaloGM/CodecademyTDDVidBits/blob/master/test/routes/create-video-test.js#L38-L80

These tests can be nested under a `description` like so: 
```
describe('POST /videos', () => {
  it('does some stuff')

  it('does some other stuff')

  describe('when the title is missing', () => {
    it('does not save video in database')
    it('responds with a 400 status code')
    it('renders the video form')
    ...etc
  })
})
```

This helps with readability and we want to write tests that are easy for other developers to read!

**Comment by GonzaloGM** [comment]
Very good feedback, @cjessett I'll make those changes and keep that in mind when making my tests :)
